const discord = require('discord.js');
const Snoowrap = require('snoowrap');
const client = new discord.Client();
let data = [];

function getRandomInt(min, max) {
  min = Math.ceil(min);
  max = Math.floor(max);
  return Math.floor(Math.random() * (max - min)) + min; //The maximum is exclusive and the minimum is inclusive
}

client.on('ready', () => {
    console.log("Connected as " + client.user.tag);
    ScrapeSubreddit();
    console.log(quotes.length);
});

client.on('message', msg => {
  if(msg.content === '&help'){
    var helpMessage = new discord.MessageEmbed()
    .setColor('#2323d6')
    .setTitle('Prequel Bot Help')
    .addFields(
      { name: 'To get a Quote', value: 'Type : &executeorder66' },
      { name: 'To get a Meme', value: 'Type : &dewit' },
      { name: 'To get Both', value: 'Type : &hellothere'}
    )
    .setTimestamp();

    msg.channel.send(helpMessage);
  }
  if (msg.content === '&hellothere') {
    var newQuote = quotes[getRandomInt(0, quotes.length)];
    msg.channel.send(newQuote);
    msg.reply(data[getRandomInt(0, data.length)].link);
  }
  if(msg.content === '&dewit'){
    msg.reply(data[getRandomInt(0, data.length)].link);
  }
  if(msg.content === '&executeorder66'){
    var newQuote = quotes[getRandomInt(0, quotes.length)];
    msg.channel.send(newQuote);
  }
});


async function ScrapeSubreddit(){
  const r = new Snoowrap({
    userAgent: 'Prequel Memes Bot for Discord',
    clientId: 'MY-YXsaOyy9PTg',
    clientSecret: '5lxm8vmB65M5Cge1AATIGQ8JYzM',
    refreshToken: '162173890537-ryu3V7Kd79u4ZxgWZuFLFIRVQmQ'
  });

  const subreddit = await r.getSubreddit('prequelMemes');
  const topPosts = await subreddit.getTop({time: 'week', limit: 100});

  topPosts.forEach((post)=>{
    data.push({
      link: post.url,
      text: post.title,
      score: post.score
    })
  });

  console.log('scraping finished');
}


var quotes = [ 
	'NUTE : Yes, yes, of coarse...ahhh...as you know, our blockade is perfectly legal, and we’d be happy to recieve the Ambassador...Happy to. -  Episode 1',
	'OBI-WAN : I have a bad feeling about this. -  Episode 1',
	'QUI-GON : These Federation types are cowards. The negotiations will be short. -  Episode 1',
	'QUI-GON : Destroyer droids! -  Episode 1',
	'TEY HOW : Sir, they’ve gone up the ventilation shaft. -  Episode 1',
	'OBI-WAN : You were right about one thing, Master. The negotiations were short. -  Episode 1',
	'BIBBLE : A communications disruption can only mean one thing. Invasion. -  Episode 1',
	'JAR JAR : Oh, noooooooooo! -  Episode 1',
	'JAR JAR : Hey, help me! Help me!! -  Episode 1',
	'QUI-GON : Let go! -  Episode 1',
	'JAR JAR : Oyi, mooie-mooie! I luv yous! -  Episode 1',
	'QUI-GON : Are you brainless? You almost got us killed! -  Episode 1',
	'JAR JAR : I spake. -  Episode 1',
	'QUI-GON : The ability to speak does not make you intelligent. Now get outta here! -  Episode 1',
	'JAR JAR : No...no! Mesa stay...Mesa yous humble servaunt. -  Episode 1',
	'QUI-GON : That wont be necessary. -  Episode 1',
	'JAR JAR : Oh boot tis! Tis demunded byda guds. Tis a live debett, tis. Mesa culled Jaja Binkss. -  Episode 1',
	'QUI-GON : I have no time for this now... -  Episode 1',
	'JAR JAR : Say what? -  Episode 1',
	'JAR JAR : Oh, nooooo! Weesa ganna.... -  Episode 1',
	'JAR JAR : ...dieeee! -  Episode 1',
	'JAR JAR : Mure? Mure did you spake??!? -  Episode 1',
	'JAR JAR : Ex-squeeze me, but da moto grande safe place would be -  Episode 1',
	'JAR JAR : Ahhh, will...on second taut...no, not willy. -  Episode 1',
	'JAR JAR : Iss embarrissing, boot... My afrai my’ve bean banished. My forgoten der Bosses would do terrible tings to my. Terrible tings if my goen back dare. -  Episode 1',
	'JAR JAR : Oh! Yousa point is well seen. Dis way! Hurry! -  Episode 1',
	'JAR JAR : Wesa goen underwater, okeyday? -  Episode 1',
	'JAR JAR : My warning yous. Gungans no liken outlaunders. Don’t expict a wern welcome. -  Episode 1',
	'BOSS NASS : Yousa cannot bees hair. Dis army of mackineeks up dare tis new weesong! -  Episode 1',
	'BOSS NASS : Wesa no like da Naboo! Un dey no like uss-ens. Da Naboo tink day so smarty den us-ens. Day tink day brains so big. -  Episode 1',
	'BOSS NASS : No, mesa no tink so. Mesa scant talkie witda Naboo, and no nutten talkie it outlaunders. Dos mackineeks no comen here! Dey not know of uss-en. -  Episode 1',
	'BOSS NASS : Wesa wish no nutten in yousa tings, outlaunder, and wesa no care-n about da Naboo. -  Episode 1',
	'BOSS NASS : Wesa give yousa una bongo. Da speedest way tooda Naboo tis goen through da core. Now go. -  Episode 1',
	'OBI-WAN : Master, whats a bongo? -  Episode 1',
	'BOSS NASS : Binkss brokeen the nocombackie law. Hisen to be pune-ished. -  Episode 1',
	'JAR JAR : Oooooh...Ouch! -  Episode 1',
	'QUI-GON : We need a navigator to get us through the planet’s core. I have saved Jar Jar Binks’ life. He owes me what you call a "life.debt." -  Episode 1',
	'BOSS NASS : Hisen live tis yos, outlauder. Begone wit him. -  Episode 1',
	'JAR JAR : Count mesa outta dis! Better dead here, den deader in da core...Yee guds, whata mesa sayin?! -  Episode 1',
	'JAR JAR : Dis is nusen. -  Episode 1',
	'OBI-WAN : Master, why do you keep dragging these pathetic life forms along with us?...Here, take over. -  Episode 1',
	'JAR JAR : Hey, ho? Where wesa goen?? -  Episode 1',
	'JAR JAR : Ooooh, maxibig..."da Force"...Wellen, dat smells stinkowiff. -  Episode 1',
	'NUTE : The invasion is on schedule, My Lord. -  Episode 1',
	'DARTH SIDIOUS : Good. I have the Senate bogged down in procedures. By the time this incident comes up for a vote, they will have no choice but to accept your control of the system. -  Episode 1',
	'NUTE : The Queen has great faith the Senate will side with her. -  Episode 1',
	'JAR JAR : What yet? Monstairs out dare! Leak’n in here, all’n sink’n, and nooooo power! You nutsen! WHEN YOUSA TINK WESA IN TROUBLE?!!!? -  Episode 1',
	'OBI-WAN : You overdid it. -  Episode 1',
	'JAR JAR : Wesa dead yet?? Oie Boie! -  Episode 1',
	'NUTE : Ah, victory! -  Episode 1',
	'OBI-WAN : What is it? -  Episode 1',
	'JAR JAR : What!!?? Oie boie! -  Episode 1',
	'JAR JAR : Iyiiyi, wesa die’n here, hey! -  Episode 1',
	'JAR JAR : No! Too scary! -  Episode 1',
	'OBI-WAN : Get up here! -  Episode 1',
	'JAR JAR : No a mighty no! -  Episode 1',
	'JAR JAR : Oie boie...mesa comen. Mesa comen! -  Episode 1',
	'OBI-WAN : That was close. -  Episode 1',
	'BIBBLE : ...how will you explain this invasion to the Senate? -  Episode 1',
	'NUTE : The Naboo and the Federation will forge a treaty that will legitimize our occupation here. I’ve been assured it will be ratified by the Senate. -  Episode 1',
	'AMIDALA : I will not co-operate. -  Episode 1',
	'RIC OLIE : ....our communications are still jammed. -  Episode 1',
	'OBI-WAN : Now stay here, and keep out of trouble. -  Episode 1',
	'JAR JAR : Ello, boyos. Disa wanna longo trip...hey? -  Episode 1',
	'JAR JAR : Tis opens?...Oooops! Many springs and things come flying out. -  Episode 1',
	'JAR JAR : Yoi! Just yoken! -  Episode 1',
	'RIC OLIE : There’s not enough power to get us to Coruscant...the hyperdrive is leaking. -  Episode 1',
	'QUI-GON : We’ll have to land somewhere to refuel and repair the ship. -  Episode 1',
	'DARTH SIDIOUS : Viceroy, find her! I want that treaty signed. -  Episode 1',
	'NUTE : My Lord, it’s impossible to locate the ship. It’s out of our range. -  Episode 1',
	'DARTH SIDIOUS : ...not for a Sith... -  Episode 1',
	'DARTH SIDIOUS : ...Viceroy, this is my apprentice. Lord Maul. He will find your lost ship. -  Episode 1',
	'RUNE : We should not have made this bargain. What will happen when the Jedi become aware of these Sith Lords? -  Episode 1',
	'JAR JAR : Sorry, nomeanen to scare yousa. -  Episode 1',
	'QUI-GON : Don’t let them send any transmissions. Be wary...I sense a disturbance in the Force. -  Episode 1',
	'JAR JAR : Dis sun doen murder tada skin. -  Episode 1',
	'CAPT. PANAKA : Wait! -  Episode 1',
	'WATTO : Coona tee-tocky malia? (What took you so long?) -  Episode 1',
	'ANAKIN : Mel tassa cho-passa... (I was cleaning the bin like you...) -  Episode 1',
	'ANAKIN : Are you an angel? -  Episode 1',
	'PADME : What? -  Episode 1',
	'ANAKIN : An angel. I’ve heard the deep space pilots talk about them. They live on the Moons of Iego I thimk. They are the most beautiful creatures in the universe. They are good and kind, and so pretty they make even the most hardened spice pirate cry. -  Episode 1',
	'PADME looks at him, not knowing what to say. PADME : I’ve never heard of angels. -  Episode 1',
	'ANAKIN : You must be one...maybe you just don’t know it. -  Episode 1',
	'PADME : You’re a funny little boy. How do you know so much? -  Episode 1',
	'ANAKIN : Since I was very little, three, I think. My Mom and I were sold to -  Episode 1',
	'PADME : You’re...a slave? -  Episode 1',
	'ANAKIN : I am a person! My name is Anakin. -  Episode 1',
	'PADME : I’m sorry. I don’t fully understand. (looking around)This is a strange world to me. -  Episode 1',
	'ANAKIN : You are a strange girl to me. -  Episode 1',
	'ANAKIN : Hit the nose! -  Episode 1',
	'WATTO : ...Here it is...a T-14 hyperdrive generator!! Thee in luck, I’m the only one hereabouts who has one...but thee might as well buy a new ship. It would be cheaper, I think...Sying of which, how’s thee going to pay for all this? -  Episode 1',
	'QUI-GON : I have 20,000 Republic dataries. -  Episode 1',
	'WATTO : Republic credits?!? Republic credits are no good out here. I need something more real... -  Episode 1',
	'QUI-GON : I don’t have anything else. But credits will do fine. -  Episode 1',
	'WATTO : No they won’ta. QUI-GON, using his mind power, waves his hand again. -  Episode 1',
	'QUI-GON : Credits will do fine. -  Episode 1',
	'WATTO : No, they won’ta. What you think you’re some kinda Jedi, waving your hand around like that? I’m a Toydarian. Mind tricks don’ta work on me-only money. No money, no parts! No deal! And no one else has a T-14 hyperdrive, -  Episode 1',
	'ANAKIN : ...wouldn’t have lasted long if I weren’t so good at fixing things. I’m making my own droid... -  Episode 1',
	'JAR JAR : Noah gain...da beings hereabouts cawazy. Wesa be robbed un crunched. -  Episode 1',
	'ANAKIN : Chess ko, Sebulba...Coo wolpa tooney rana. (Careful, -  Episode 1',
	'SEBULBA : Tooney rana nu pratta dunko, shag. (Connected?? Whada you mean, slave?) -  Episode 1',
	'SEBULBA : Una noto wo shag, me wompity du pom pom. (If you weren’t a slave, I’d squash you right now.) -  Episode 1',
	'ANAKIN : Eh, chee bana do mullee ra. (Yeah, it’d be a pity if you had to pay for me.) -  Episode 1',
	'SHMI : All slaves have transmitters placed inside their bodies somewhere. -  Episode 1',
	'JAR JAR : How wude. -  Episode 1',
	'PADME : I can’t believe there is still slavery in the galaxy. The -  Episode 1',
	'SHMI : The Republic doesn’t exist out here...we must survive on our own. -  Episode 1',
	'ANAKIN : Have you ever seen a Podrace? -  Episode 1',
	'ANAKIN : I saw your laser sword. Only Jedi carry that kind of weapon. -  Episode 1',
	'QUI-GON : Perhaps I killed a Jedi and stole it from him. -  Episode 1',
	'ANAKIN : I don’t think so... No one can kill a Jedi Knight. -  Episode 1',
	'QUI-GON : I can see there’s no fooling you...You mustn’t let anyone know about us...we’re on our way to Coruscant, the central system in the Republic, on a very important mission, and it must be kept secret. -  Episode 1',
	'ANAKIN : I can help! I can fix anything! -  Episode 1',
	'JAR JAR : Wit no-nutten mula to trade. -  Episode 1',
	'SHMI : Gambling. Everything here revolves around betting on those awful races. -  Episode 1',
	'ANAKIN : But Mom, I love it...and they need help...they’re in trouble. The prize money would more than pay for the parts they need. JAR JAR : Wesa ina pitty bad goo. -  Episode 1',
	'ANAKIN : Is that a yes? That is a yes! -  Episode 1',
	'PADME : Are you sure about this? Trusting our fate to a boy we hardly know. -  Episode 1',
	'PADME : Well, I don’t approve. -  Episode 1',
	'WATTO : Patta go bolla! -  Episode 1',
	'ANKAIN : No batta! -  Episode 1',
	'WATTO : Pedunky. Maa kee cheelya. -  Episode 1',
	'ANAKIN : Bayno, Bayno! -  Episode 1',
	'KITSTER : Wow, a real Astro Droid...how’d you get so lucky? -  Episode 1',
	'KITSTER : What? With this?? -  Episode 1',
	'WALD : Annie, Jesko na joka. 9You are such a joke, Annie.) -  Episode 1',
	'AMEE : You’ve been working on that thing for years. It’s never going to run. -  Episode 1',
	'SEEK : Come on, let’s go play ball. Keep it up, Annie, and you’re gonna be bug squash. -  Episode 1',
	'ANAKIN : Hey! Jar Jar! Stay away from those energy binders... -  Episode 1',
	'ANAKIN : If your hand gets caught in that beam, it will go numb for hours. -  Episode 1',
	'KITSTER : But you don’t even know if this thing will run. -  Episode 1',
	'ANAKIN : It will. -  Episode 1',
	'ANAKIN : There are so many! Do they all have a system of planets? -  Episode 1',
	'ANAKIN : Has anyone been to them all? -  Episode 1',
	'ANAKIN : I want to be the first one to see them all... Ouch! -  Episode 1',
	'ANAKIN : What are you doing? -  Episode 1',
	'QUI-GON : Checking your blood for infections. -  Episode 1',
	'QUI-GON : I need a midi-chlorian count. -  Episode 1',
	'QUI-GON : What are your readings? -  Episode 1',
	'QUI-GON : Here’s a signal check. -  Episode 1',
	'OBI-WAN : Strange. The transmission seems to be in good order, but the reading’s off the chart...over twenty thousand. -  Episode 1',
	'OBI-WAN : Even Master Yoda doesn’t have a midi-chlorian count that high! -  Episode 1',
	'OBI-WAN : What does it mean? -  Episode 1',
	'ANAKIN : Hook ‘em up, Kitster. I won’t be long. Where’s Qui-Gon? -  Episode 1',
	'QUI-GON : Patience, my blue friend. You’ll have your winnings before the suns set, and we’ll be far away from here. -  Episode 1',
	'WATTO : Don’t get me wrongo. I have great faith in the boy. He’s a credit to your race, but Sebulba there is going to win, I think. -  Episode 1',
	'WATTO : He always wins. I’m betting heavily on Sebulba. -  Episode 1',
	'QUI-GON : I’ll wager my new racing pod against...say...the boy and his mother. -  Episode 1',
	'WATTO : A Pod for slaves. I don’t think so...well, poerhaps. Just one...the mother, maybe...the boy isn’t for sale. -  Episode 1',
	'WATTO : No Pod’s worth two slaves...not by a long shot...one slave or nothing. -  Episode 1',
	'QUI-GON : The boy, then... -  Episode 1',
	'WATTO : We’ll let fate decide. Blue it’s the boy, red his mother... -  Episode 1',
	'WATTO : Bonapa keesa pateeso, o wanna meetee chobodd. -  Episode 1',
	'THREEPIO : Oh my! Space travel sounds rather perilous. -  Episode 1',
	'THREEPIO : I can assure you they will never get me onto one of those dreadful starships! -  Episode 1',
	'KITSTER : This is so wizard! I’m sure you’ll do it this time, -  Episode 1',
	'KITSTER : Finish the race, of course! -  Episode 1',
	'WATTO : You! You swindled me! You knew the boy was going to win! Somehow you knew it! I lost everything. -  Episode 1',
	'QUI-GON : Whenever you gamble, my freind, eventually you’ll lose. Bring the parts to the main hanger. I’ll come by your shop later so you can release the boy. -  Episode 1',
	'QUI-GON : Would you like to discuss it with the Hutts...I’m sure they can settle this. -  Episode 1',
	'WATTO : No, no! I want no more of your tricks! Take him! -  Episode 1',
	'ANAKIN : Ah, gee...enough of this... -  Episode 1',
	'PADME : We owe you everything. -  Episode 1',
	'OBI-WAN : Why do I sense we’ve picked up another pathetic life form...? -  Episode 1',
	'QUI-GON : It’s the boy who’s responsible for getting those parts. -  Episode 1',
	'ANAKIN : He said I cheated. -  Episode 1',
	'QUI-GON : Did you? -  Episode 1',
	'ANAKIN : No! -  Episode 1',
	'SHMI : Oh, my goodness, That’s wonderful. -  Episode 1',
	'ANAKIN : What?!? -  Episode 1',
	'ANAKIN : Did you hear that, Mom? Was that part of the prize, or what? -  Episode 1',
	'QUI-GON : Let’s just say Watto has learned an important lesson about gambling. -  Episode 1',
	'ANAKIN : A Jedi! Mighty blasters, you mean I get to go with you in your starship and everything?! -  Episode 1',
	'QUI-GON : Anakin, training to be a Jedi will not be a easy challenge. And if you succeed, it will be a hard life. -  Episode 1',
	'ANAKIN : But it’s what I want. What I’ve always dreamed about. Can I go, -  Episode 1',
	'QUI-GON : This path has been placed for you, Annie; the choice to take it is yours alone. -  Episode 1',
	'ANAKIN : I want to go. -  Episode 1',
	'ANAKIN : Yipee!! -  Episode 1',
	'QUI-GON : I tried to free your mother, Annie, but Watto wouldn’t have it. -  Episode 1',
	'SHMI : Son, my place is here. My future is here. It is time for you to let go...to let go of me. I cannot go with you. -  Episode 1',
	'ANAKIN : I want to stay with you. I don’t want things to change. -  Episode 1',
	'ANAKIN : Well, Threepio, I’m free...and I’m going away...in a starship... -  Episode 1',
	'THREEPIO : Master, Annie, you are my maker, and I wish you well. Although -  Episode 1',
	'ANAKIN : I’m sorry I wasn’t able to finish you, Threepio...give you coverings and all... I’m going to miss working on you. You’ve been a great pal. I’ll make sure Mom doesn’t sell you or anything. Bye. -  Episode 1',
	'THREEPIO : Sell me?!? -  Episode 1',
	'KITSTER : There are so many of us who want you to stay, Annie... You’re a hero. -  Episode 1',
	'KITSTER : Well. -  Episode 1',
	'KITSTER : Thank’s for every moment you’ve been here. You’re my best friend. -  Episode 1',
	'ANAKIN : Will I ever see you again? -  Episode 1',
	'SHMI : What does your heart tell you? -  Episode 1',
	'JIRA : Can I give you a hug -  Episode 1',
	'ANAKIN : Sure. -  Episode 1',
	'JAR JAR : Da Queens- a bein grossly nice, mesa tinks. (he looks around) -  Episode 1',
	'QUI-GON : I must speak with the Jei Council immediately, Your Honor. The situation has become more complicated. -  Episode 1',
	'JAR JAR : Dissen all pitty odd to my. -  Episode 1',
	'MACE WINDU : A Sith Lord?!? -  Episode 1',
	'KI-ADI : Impossible! The Sith have been extinct for a millenium. -  Episode 1',
	'QUI-GON : A boy... his cells have the highest concentration of midi-chlorians I have seen in a life form. It is possible he was conceived by the midi-chlorians. -  Episode 1',
	'PALPATINE : If the Federation moves to defer the motion...Your Majesty, -  Episode 1',
	'VALORUM : Overruled. -  Episode 1',
	'ASSEMBLY : Vote now! Vote now! Vote now! -  Episode 1',
	'MAS AMEDDA : Thew Supreme Chancellor requests a recess. Tomorrow we will begin the vote. -  Episode 1',
	'ANAKIN : A ship...a cup...a speeder. -  Episode 1',
	'YODA : Good, good, young one. How feel you? -  Episode 1',
	'ANAKIN : Cold, sir. -  Episode 1',
	'YODA : Afraid are you? -  Episode 1',
	'ANAKIN : No, sir. -  Episode 1',
	'MACE WINDU : Afraid to give up your life? -  Episode 1',
	'ANAKIN : I don’t think so. -  Episode 1',
	'KI-ADI : Your thoughts dwell on your mother. -  Episode 1',
	'ANAKIN : I miss her. -  Episode 1',
	'YODA : Afraid to lose her..I think. -  Episode 1',
	'YODA : Eveything. Fear is the path to the dark side... fear leads to anger... anger leads to hate.. hate leads to suffering. -  Episode 1',
	'YODA : A Jedi must have the deepest commitment, the most serious mind. I sense much fear in you. -  Episode 1',
	'JAR JAR : Mesa wonder why da guds invent pain? -  Episode 1',
	'JAR JAR : Yousa tinken yousa people ganna die? -  Episode 1',
	'JAR JAR : Gungans ganna get pasted too, eh? -  Episode 1',
	'JAR JAR : Gungans do die’n without a fight.... wesa warriors. Wesa gotta grand army. Dat why you no liken us, metinks. -  Episode 1',
	'AMIDALA : I will sign no treaty, Senator. My fate will be no different from that of our people. Captain! -  Episode 1',
	'MACE WINDU : His cells contain a high concentration of midi-chlorians. -  Episode 1',
	'KI-ADI : The Force is strong with him. -  Episode 1',
	'QUI-GON : He’s to be trained, then. -  Episode 1',
	'MACE WINDU : No. He will not be trained. -  Episode 1',
	'QUI-GON : No??!! -  Episode 1',
	'MACE WINDU : He is too old. There is already too much anger in him. -  Episode 1',
	'QUI-GON : He is the chosen one...you must see it. -  Episode 1',
	'YODA : Clouded, this boy’s future is. Masked by his youth. -  Episode 1',
	'QUI-GON : I will trin him, then. I take Anakin as my Padawan learner. -  Episode 1',
	'YODA : An apprentice, you have, Qui-Gon. Impossible, to take on a second. -  Episode 1',
	'MACE WINDU : We forbid it. -  Episode 1',
	'QUI-GON : Obi-Wan is ready... -  Episode 1',
	'OBI-WAN : I am ready to face the trials. -  Episode 1',
	'YODA : Ready so early, are you? What know you of ready? -  Episode 1',
	'QUI-GON : Headstrong....and he has much to learn about the living Force, but he is capabe. There is little more he will learn from me. -  Episode 1',
	'YODA : Our own council we will keep on who is ready. More to learn, he has... -  Episode 1',
	'MACE WINDU : Now is not the time for this...the Senate is voting for a new -  Episode 1',
	'YODA : And draw out the Queen’s attacker. -  Episode 1',
	'KI-ADI : Events are moving fast...too fast. -  Episode 1',
	'MACE WINDU : Go with the Queen to Naboo and discover the identity of the dark warrior. That is the clue we need to unravel this mystery of the Sith. -  Episode 1',
	'YODA : Young Skywalker’s fate will be decided later. -  Episode 1',
	'QUI-GON : I brought Anakin here; he must stay in my charge. He has nowhere else to go. -  Episode 1',
	'MACE WINDU : He is your ward, Qui-Gon...we will not dispute that. -  Episode 1',
	'YODA : Train him not. Take him with you, but train him not! -  Episode 1',
	'MACE WINDU : Protect the Queen, but do not intercede if it comes to war until we have the Senate’s approval. -  Episode 1',
	'YODA : May the Force be with you. -  Episode 1',
	'OBI-WAN : It is not disrespect, Master, it is the truth. -  Episode 1',
	'QUI-GON : From your point of view.... -  Episode 1',
	'OBI-WAN : The boy is dangerous...they all sense it. Why can’t you? -  Episode 1',
	'QUI-GON : His fate is uncertain, not dangerous. The Council will decide -  Episode 1',
	'ANAKIN : Master Qui-Gon, sir, I do not wish to be a problem. -  Episode 1',
	'QUI-GON : You won’t be, Annie....I’m not allowed to train you, so I want you to watch me and be mindful...always remember, your focus determines your reality. Stay close to me and you will be safe. -  Episode 1',
	'ANAKIN : Master, sir...I’ve been wondering...what are midi-chlorians? -  Episode 1',
	'QUI-GON : Midi-chlorians are a microcopic lifeform that reside within all living cells and communicates with the Force. -  Episode 1',
	'ANAKIN : They live inside of me? -  Episode 1',
	'QUI-GON : In your cells. We are symbionts with the midi-chlorians. -  Episode 1',
	'QUI-GON : Your Highness, it is our pleasure to continue to serve and protect you. -  Episode 1',
	'JAR JAR : Wesa goen home! -  Episode 1',
	'NUTE : Yes, my Lord. -  Episode 1',
	'DARTH SIDIOUS : Viceroy, is the planet secure? -  Episode 1',
	'NUTE : Yes, my Lord, we have taken over the last pockets of primitive life forms. We are in complete control of the planet now. -  Episode 1',
	'DARTH SIDIOUS : Good. I will see to it that in the Senate, things stay as they are. I am sending Darth Maul to join you. He will deal with the Jedi. -  Episode 1',
	'NUTE : Yes, my Lord. -  Episode 1',
	'RUNE : A Sith lord here with us?!! -  Episode 1',
	'ANAKIN : ...and that one? -  Episode 1',
	'JAR JAR : Ello! Where das everybody? -  Episode 1',
	'JAR JAR : Dare-sa nobody dare. All gone. Some kinda fight, I tink. Sorry, no Gungas...no Gungas. -  Episode 1',
	'QUI-GON : Do you know where they are? -  Episode 1',
	'BOSS NASS : Yousa doen grand. Jar Jar bringen da Naboo together. -  Episode 1',
	'JAR JAR : Oh, no, no, no... -  Episode 1',
	'BOSS NASS : So, wesa maken yousa Bombad General. -  Episode 1',
	'JAR JAR : General??! Oh, no.. -  Episode 1',
	'PADME : What is the situation? -  Episode 1',
	'BOSS NASS : Wesa ready to do are-sa part. -  Episode 1',
	'QUI-GON : Stay in that cockpit. -  Episode 1',
	'ANAKIN : We gotta do something, Artoo. -  Episode 1',
	'ANAKIN : All right, thanks Artoo! Great idea! I’ll take over. -  Episode 1',
	'ANAKIN : Where’s the trigger? Oops, wrong one.. Maybe this one.... -  Episode 1',
	'ANAKIN : Yeah, all right. "Droid blaster." Yeah! -  Episode 1',
	'ANAKIN : Oops...shield up! Always on the right...shields always on the right. -  Episode 1',
	'ANAKIN : I know we’re moving. I’ll shut the energy drive down. -  Episode 1',
	'ANAKIN : Oops!! Wrong one. -  Episode 1',
	'ANAKIN : I’m not doing anything! -  Episode 1',
	'ANAKIN : I know...I didn’t push anything. -  Episode 1',
	'ANAKIN : The Autopilot is searching for what other ships? -  Episode 1',
	'ANAKIN : There is no manual override, Artoo. You’ll have to rewire it or something. -  Episode 1',
	'ANAKIN : Look! There they are! That’s where the autopilot is taking us. -  Episode 1',
	'ANAKIN : Whoo, boy! This is tense! -  Episode 1',
	'ANAKN : : Oops! Artoo, get us off Autopilot! -  Episode 1',
	'ANAKIN : I’ve got control? -  Episode 1',
	'ANAKIN : Okay, let’s go left! -  Episode 1',
	'ANAKIN : Yes...I’ve got control. You did it, Artoo! -  Episode 1',
	'ANAKIN : Go back!?! Qui-Gon told me to stay in this cockpit and that’s what I’m gonna do. Now c’mon! -  Episode 1',
	'ANAKIN : Oops! Whoa! -  Episode 1',
	'ANAKIN : I’ll try spinning, that’s a good trick. -  Episode 1',
	'ANAKIN : I know we’re in trouble! Hang on! The way out of this mess is the way we got into it. -  Episode 1',
	'ANAKIN : Which one? This one? -  Episode 1',
	'ANAKIN : I know, Artoo! This isn’t Podracing! -  Episode 1',
	'ANAKIN : We’re hit! -  Episode 1',
	'ANAKIN : Great gobs of bantha poo-doo! -  Episode 1',
	'ANAKIN : I’m trying to stop! I’m trying to stop! Whoa! -  Episode 1',
	'ANAKIN : All right! All right! Get the system started! -  Episode 1',
	'ANAKIN : Everything’s overheated. All the lights are red. -  Episode 1',
	'NUTE : After her! This one is a decoy! -  Episode 1',
	'OBI-WAN : Master! Master! -  Episode 1',
	'QUI-GON : It is too late...It’s... -  Episode 1',
	'OBI-WAN : No! -  Episode 1',
	'QUI-GON : Obi-Wan promise...promise me you’ll train the boy... -  Episode 1',
	'OBI-WAN : Yes, Master... -  Episode 1',
	'QUI-GON : He is the chosen one...he will...bring balance...train him! -  Episode 1',
	'ANAKIN : Yes...we have ignition. -  Episode 1',
	'ANAKIN : Not if I can help it! Shields up! -  Episode 1',
	'ANAKIN : This should stop them. -  Episode 1',
	'ANAKIN : ...and take this! -  Episode 1',
	'ANAKIN : Darn...I missed! -  Episode 1',
	'ANAKIN : Let’s get out of here! -  Episode 1',
	'ANAKIN : Now, this is Podracing! Whoopee! -  Episode 1',
	'TEY HOW : Sir, we’re losing power... There is some problem with the main reactor... -  Episode 1',
	'DOFINE : Impossible!! I don’t... -  Episode 1',
	'BRAVO TWO : What’s that?? It’s blowing up from the inside. -  Episode 1',
	'RIC OLIE : I don’t know, we didn’t hit it. -  Episode 1',
	'BRAVO TWO : He flew into the hold, behind the deflector shield and blasted the main reactor... -  Episode 1',
	'BRAVO THREE : Amazing... They don’t teach that in the academy. -  Episode 1',
	'RIC OLIE : We’re all accounted for. Who flew that ship? -  Episode 1',
	'ANAKIN : I’m not going to get into trouble, am I? -  Episode 1',
	'PADME : Now, Viceroy, you are going to have to go back to the Senate and explain all this. -  Episode 1',
	'PALPATINE : It’s good to be home. Your boldness has saved our people, Your -  Episode 1',
	'YODA : Confer on you, the level of Jedi Knight the Coucil does. But agree on you taking this boy as your Padawan learner, I do not. -  Episode 1',
	'ANAKIN : What will happen to me now? -  Episode 1',
  'OBI-WAN : I am your Master now. You will become a Jedi, I promise. -  Episode 1',
  'MACE WINDU : You know, M’Lady, Count Dooku was once a Jedi. He wouldn’t assassinate anyone, it is not in his character. - Episode 2',
	'KI-ADI-MUNDI : He is a political idealist, not a murderer. - Episode 2',
	'JAR JAR : Obi! Obi! Obi! Mesa sooo smilen to see’en yousa. Wahoooooo! - Episode 2',
	'JAR JAR : ...and this, I take it, is your apprentice... Nooooooooo! Annie? Noooooooo! Little Bitty Annie? Nooooooo! Yousa so biggen! Yiyiyiyyi! Annie!! Mesa no believen. - Episode 2',
	'JAR JAR : Annie! Annie! Yiyiyiyiyiyiiii! - Episode 2',
	'JAR JAR : Lookie... lookie... Oops!... Oh, dear, I’m afraid I’ve forgotten myself again. - Episode 2',
	'ANAKIN : So have you... grown more beautiful, I mean... and much shorter... for a Senator, I mean. - Episode 2',
	'PADMÉ : Oh Annie, you’ll always be that little boy I knew on Tatooine. - Episode 2',
	'JAR JAR : Mesa busten wit happiness seein Yousa again, Annie. Deesa bad times, bombad times. - Episode 2',
	'ANAKIN : She didn’t even recognise me, Jar Jar. I thought about her every day since we parted... and she’s forgotten me completely. - Episode 2',
	'JAR JAR : Shesa happy. Happier den mesa see-en her in longo time. - Episode 2',
	'ANAKIN : She covered that camera. I don’t think she liked me watching her. - Episode 2',
	'OBI-WAN : You’re using her as bait?? - Episode 2',
	'OBI-WAN : Because of your mother? - Episode 2',
	'ANAKIN : I’d rather dream of Padmé. Just Being around her again is... intoxicating. - Episode 2',
	'ANAKIN : She’s not like the others in the Senate, Master. - Episode 2',
	'ANAKIN : That was wacky! I almost lost you in the traffic. - Episode 2',
	'ANAKIN : Don’t say that Master... You’re the closest thing I have to a father... I love you. I don’t want to cause you pain. - Episode 2',
	'ELAN SLEAZEBAGGANO : Wanna buy some death sticks?\nOBI-WAN : You don’t want to sell me death- sticks.\nELAN : I don’t want to sell you death- sticks.\nOBI-WAN : You want to go home and rethink your life.\nELAN : I want to go home and rethink my life - Episode 2',
	'JAR JAR : Yousa betchen mesa bottums. - Episode 2',
	'PADMÉ : Please don’t look at me like that\nANAKIN : Why not?\nPADMÉ : Because I can see what you’re thinking.\nANAKIN : Ahh... so, you have Jedi powers too?\nPADMÉ : It makes me feel uncomfortable. - Episode 2\nPADMÉ : It must be difficult having sworn your life to the Jedi... not being able to visit the places you like... or do the things you like...\nANAKIN : Or be with the people I love.\nPADMÉ : Are you allowed to love? I thought that was forbidden for a Jedi.\mANAKIN : Attachment is forbidden. Possession is forbidden. Compassion, which I would define as unconditional love, is central to a Jedi’s life, so you might say we’re encouraged to love. - Episode 2',
	'OBI-WAN : That’s impossible... perhaps the archives are incomplete. - Episode 2',
	'JOCASTA NU : The archives are comprehensive and totally secure, my young Jedi. One thing you may be absolutely sure of - if an item does not appear in our records, it does not exist! - Episode 2',
	'YODA : An interesting puzzle. Gather round the map reader, younglings. Master Obi-Wan has lost a planet. Find it, we will try... - Episode 2',
	'YODA : Truly wonderful, the mind of a child is. Uncluttered. To the centre of the pull of gravity go, and find your planet you will. - Episode 2',
	'ANAKIN : I don’t like sand. It’s coarse and rough and irritating, and it gets everywhere. Not like here. Here everything’s soft... and smooth... - Episode 2',
	'ANAKIN : I’m sorry. When I’m around you, my mind is no longer my own. - Episode 2',
	'OBI-WAN : He has a... an emotional connection with her. It’s been there since he was boy. Now he’s confused... distracted. - Episode 2',
	'ANAKIN : I’m not really supposed to do that... for fun, I mean. If Master Obi-Wan were here, he’d be very grumpy - Episode 2',
	'ANAKIN : It doesn’t work around you. My mind is always a muddle... I can only think of you. - Episode 2',
	'ANAKIN : From the moment I met you, all those years ago, a day hasn’t gone by when I haven’t thought of you. And now that I’m close to you again, I’m in agony. The closer I get to you, the worse it gets. The thought of not being with you makes my stomach turn over - my mouth goes dry. I feel dizzy. I can’t breathe. I’m haunted by the kiss you should never have given me. My heart is beating, hoping that kiss will not become a scar. You are in my very soul, tormenting me. What can I do? I will do anything you ask... - Episode 2',
	'PADME : You listen. We live in a real world. Come back to it. You’re studying to become a Jedi Knight. I’m a Senator. If you follow your thoughts through to conclusion, they will take us to a place we cannot go... regardless of the way we feel about each other. - Episode 2',
	'ANAKIN : Then you do feel something! There’s an extraordinary connection between us. You can’t deny that. - Episode 2',
	'PADME : Annie, it doesn’t make any difference. Jedi aren’t allowed to marry. You swore an oath, remember? You’d be expelled from the Order. I will not let you give up your responsibilities... your future, for me. - Episode 2',
	'PADME : I am not going to give into this. I’m not going to throw my life away. I have more important things to do than fall in love. - Episode 2',
	'OBI-WAN : That is... good news. - Episode 2',
  'OBI-WAN : *Visible Confusion* - Episode 2',
	'OBI-WAN : That’s why I’m here. - Episode 2',
	'ANAKIN : They only work on the weak-minded. You are anything but weak-minded. - Episode 2',
	'ANAKIN : I don’t think the system works. - Episode 2',
	'WATTO : What? I don’t know you... What can I do for you? You look like a Jedi. Whatever it is... I didn’t do it. - Episode 2',
	'WATTO : You are Annie! It is you! You little womp rat. - Episode 2',
	'WATTO : You sure sprouted Weehoo! A Jedi! Waddya know? Hey, maybe you couldda help wit some daedbeats who owe... - Episode 2',
	'C-3PO : Naked. If you pardon the expression. You see, when Master Annie made me, he never quite found the time to give me any outer covering. It’s so humiliating. How would you like it if you had to go around with all your circuits showing? - Episode 2',
	'C-3PO : Ooooh! That’s tickles. - Episode 2',
  'JAR JAR : Supreme Chancellor... my august colleagues, I would be proud to propose the motion in question. This is a grave situation, and I’m sure Senator Amidala, and the Queen of Naboo would agree. - Episode 2',
  'ANAKIN : I killed them. I killed them all, they’re dead; every single one of them, and not just the men…. But the women…. And the children too. They’re like animals and I slaughtered them like animals. I hate them! – Episode 2',
  'JAR JAR : In response to the direct threat to the Republic from the Confederacy of Independent Systems, I propose that the Senate gives immediate emergency powers to the Supreme Chancellor. - Episode 2',
	'PALPATINE : It is with great reluctance that I have agreed to this calling. I love democracy... I love the Republic. - Episode 2',
	'NUTE GUNRAY : Get on with it. Carry out the sentence. I want to see her suffer. - Episode 2',
  "PADMÉ : I’m not afraid to die. I’ve been dying a little bit each day since you came back into my life\nANAKIN : What are you talking about?\nPADMÉ : I love you.\nANAKIN : You love me?! I thought we decided not to fall in love. That we would be forced to live a lie. That it would destroy our lives...\nPADMÉ : I think our lives are about to be destroyed anyway. My love for you is a puzzle, Annie, for which I have no answers. I can’t control it... and now I don’t care. I truly, deeply love you, and before we die I want you to know.\nANAKIN : I have no desire to be cured of this love either. Long or short, I vow to spend the rest of my life with you - Episode 2",
  'NUTE GUNRAY : Foul!! She can’t do that... shoot her or something! - Episode 2',
	'COUNT DOOKU : You have fought gallantly. Worthy of recognition in the history archives of the Jedi Order. Now it is finished. Surrender - and your lives will be spared. - Episode 2',
	'MACE WINDU : We will not be hostages for you to barter with Dooku. - Episode 2',
	'COUNT DOOKU : Kenobi, isn’t it? As you can see, my Jedi powers are far beyond yours. Now, back down. - Episode 2',
	'OBI-WAN : I don’t think so. - Episode 2',
	'COUNT DOOKU : That’s brave of you, boy - but foolish. I would have thought you’d have learnt your lesson. - Episode 2',
	'ANAKIN : I’m a slow learner. - Episode 2',
	'YODA : Count Dooku. No interest in contests, do I have. - Episode 2',
	'YODA : Not victory, a defeat, it was... Master Obi-Wan. Begun, the Clone War has - Episode 2',
	'ANAKIN: This is where the fun begins. - Episode 3',
	'OBI-WAN: Flying is for droids. - Episode 3',
	'OBI-WAN: Oh, I have a bad feeling about this. - Episode 3',
	'OBI-WAN: I sense a trap. - Episode 3',
	'GENERAL GRIEVOUS: What’s the situation, Captain? - Episode 3',
	'GENERAL GRIEVOUS: Just as Count Dooku predicted. - Episode 3',
	'OBI-WAN: You still have much to learn. - Episode 3',
	'SUPER BATTLE DROID R77: I have a bad feeling about this. - Episode 3',
	'OBI-WAN: No! - Episode 3',
	'DROID 2: Roger, roger. - Episode 3',
	'OBI-WAN: Oh, it’s you . . . - Episode 3',
	'OBI-WAN: This time we will do it together. - Episode 3',
	'PALPATINE: Get help! You’re no match for him. He’s a Sith Lord. - Episode 3',
	'OBI-WAN: Chancellor Palpatine, Sith Lords are our specialty. - Episode 3',
	'COUNT DOOKU: I’ve been looking forward to this. - Episode 3',
	'ANAKIN: My powers have doubled since the last time we met, Count. - Episode 3',
	'COUNT DOOKU: Good. Twice the pride, double the fall. - Episode 3',
	'PALPATINE: Dew it!! - Episode 3',
	'PALPATINE: You did well, Anakin. He was too dangerous to be kept alive. - Episode 3',
	'ANAKIN: I shouldn’t have done that, Chancellor. It’s not the Jedi way. - Episode 3',
	'ANAKIN: He seems to be all right. No broken bones, breathing’s all right. - Episode 3',
	'ANAKIN: His fate will be the same as ours. - Episode 3',
	'GENERAL GRIEVOUS: Fire the emergency booster engines. - Episode 3',
	'OBI-WAN: Did I miss something? - Episode 3',
	'OBI-WAN: Oops. - Episode 3',
	'OBI-WAN: Don’t look at me. I don’t know. - Episode 3',
	'GENERAL GRIEVOUS: Activate ray shields. - Episode 3',
	'OBI-WAN: Wait a minute, how’d this happen! We’re smarter than this. - Episode 3',
	'ANAKIN: You’re the Master. I’m just a hero. - Episode 3',
	'SUPER BATTLE DROID: Don’t move, dummy. Ouch! Zap this. - Episode 3',
	'GENERAL GRIEVOUS: Oh yes, the Negotiator.. - Episode 3',
	'OBI-WAN: That depends upon your point of view. Hah! - Episode 3',
	'GENERAL GRIEVOUS: Anakin Skywalker ... I was expecting someone with your reputation to be a little older. - Episode 3',
	'ANAKIN: General Grievous. You’re shorter than I expected. - Episode 3',
	'GENERAL GRIEVOUS: Jedi scum . . . - Episode 3',
	'GENERAL GRIEVOUS: Your lightsabers will make a fine addition to my collection. - Episode 3',
	'GENERAL GRIEVOUS: Time to abandon ship. - Episode 3',
	'OBI-WAN: Not to worry, we’re still flying half the ship. - Episode 3',
	'OBI-WAN: Another happy landing. - Episode 3',
	'GENERAL GRIEVOUS: It will be done, My Lord. - Episode 3',
	'MACE: You are on this Council, but we do not grant you the rank of Master. - Episode 3',
	'ANAKIN: What? ! How can you do this?? This is outrageous, it’s unfair . . . I’m more powerful than any of you. How can you be on the Council and not be a Master? - Episode 3',
	'MACE: Take a seat, young Skywalker. - Episode 3',
	'ANAKIN: Forgive me, Master. - Episode 3',
	'Kl-ADI-MUNDI: What about the droid attack on the Wookiees? - Episode 3',
	'MACE: It is critical we send an attack group there, immediately! - Episode 3',
	'PALPATINE: Did you ever hear the tragedy of Darth Plagueis "the wise"? I thought not. It’s not a story the Jedi would tell you. It’s a Sith legend. Darth Plagueis was a Dark Lord of the Sith, so powerful and so wise he could use the Force to influence the midi-chlorians to create life ... He had such a knowledge of the dark side that he could even keep the ones he cared about from dying. The dark side of the Force is a pathway to many abilities some consider to be unnatural. He became so powerful . . . the only thing he was afraid of was losing his power, which eventually, of course, he did. Unfortunately, he taught his apprentice everything he knew, then his apprentice killed him in his sleep. Plagueis never saw it coming. It’s ironic he could save others from death, but not himself. -Episode 3',
	'ANAKIN: Is it possible to learn this power? - Episode 3',	
	'OBI-WAN: You are strong and wise, Anakin, and I am very proud of you. – Episode 3',
	'OBI-WAN: Good-bye, old friend. May the Force be with you. - Episode 3',
	'JAR JAR: Helloo Annie. Good en to see yousa . . . - Episode 3',
	'JAR JAR: Oopsin da Chancellor!! So sorry, Your Highness, sir. - Episode 3',
	'OBI-WAN: Hello, there! - Episode 3',
	'GENERAL GRIEVOUS: General Kenobi, you are a bold one. - Episode 3',
	'GENERAL GRIEVOUS: You fool. I have been trained in your Jedi arts by Count Dooku himself. - Episode 3',
	'GENERAL GRIEVOUS: Army or not, you must realize you are doomed. - Episode 3',
	'OBI-WAN: Oh I don’t think so. - Episode 3',
	'OBI-WAN: So uncivilized . . . - Episode 3',
	'PALPATINE: I am the Senate! - Episode 3',
	'PALPATINE: It’s treason, then. - Episode 3',
	'PALPATINE: No! No! You will die! - Episode 3',
	'MACE WlNDU: Aarrrrggghhhhh . . . - Episode 3',
	'MACE WlNDU: Aarrrrggghhhhh . . . - Episode 3',
	'PALPATINE: Ahhhhhhh . . . ahhhhhhh . . . ahhhhhhh . . . - Episode 3',
	'MACE WINDU: He is too dangerous to be kept alive. - Episode 3',
	'PALPATINE: Power! Unlimited power! - Episode 3',
	'ANAKIN: What have I done? - Episode 3',
	'DARTH SIDIOUS: The time has come. Execute Order Sixty-Six. - Episode 3',
	'CLONE COMMANDER CODY: It will be done, My Lord. - Episode 3',
	'DARTH SIDIOUS: Execute Order Sixty-Six. - Episode 3',
	'CLONE COMMANDER BACARA: It will be done, My Lord. - Episode 3',
	'DARTH SIDIOUS: Execute Order Sixty-Six. - Episode 3',
	'CLONE PILOT: It will be done, My Lord. - Episode 3',
	'DABTH SIDIOUS: The time has come. Execute Order Sixty-Six. - Episode 3',
	'CLONE COMMANDER GREE: It will be done, My Lord. - Episode 3',
	'YOUNGLINGS: Master Skywalker, there are too many of them. What are we going to do? - Episode 3',
	'PALPATINE: The attempt on my life has left me scarred and deformed - Episode 3',
	'PADME: So this is how liberty dies, with thunderous applause . . . - Episode 3',
	'NUTE GUNRAY: The war is over. Lord Sidious promised us peace ... we only want . . AAAAAAAAAAAAAHHHHHHHH. - Episode 3',
	'ANAKIN: Because of Obi-Wan? - Episode 3',
	'ANAKIN: You turned her against me! - Episode 3',
	'ANAKIN: Don’t lecture me, Obi-Wan. I see through the lies of the Jedi. - Episode 3',
	'ANAKIN: If you’re not with me, you’re my enemy. - Episode 3',
	'OBI-WAN: Only a Sith deals in absolutes - Episode 3',
	'ANAKIN: From my point of view, the Jedi are evil. - Episode 3',
	'OBI-WAN: It’s over, Anakin. I have the high ground. - Episode 3',
	'ANAKIN: You underestimate my power! - Episode 3',
	'ANAKIN: I HATE YOU!!! - Episode 3',
	'DARTH VADER: No! - Episode 3',
];